version: '2'
services:
  mjpg-streamer:
    build:
      context: .
    restart: always
    image: crazycurly/mjpg-streamer
    environment:
      - ENV_RESOLUTION=1280x720
      - ENV_FPS=30
      - ENV_CAMERA=/dev/video0
    devices:
      - /dev/video0
    ports:
      - 8080:8080